# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Feature Branch
on:
  pull_request:
  push:
    branches:
      - 'main'
jobs:
  test:
    name: Running Unit-Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: name npm install
        run: npm install
      - name: Test
        run: npm test 
        

